import type { Mods } from "../types";
import type { UnlockRule } from "./upgrades";

// Active abilities. Every one either applies a timed buff or fires an instant
// effect; there is no third category, which keeps the engine small.

export type InstantEffect =
  | "heart_burst"
  | "spawn_golden"
  | "spawn_treasure"
  | "reset_cooldowns"
  | "fill_energy"
  | "max_combo"
  | "boss_strike"
  | "free_upgrade"
  | "offline_recall"
  | "mission_progress"
  | "challenge_progress"
  | "pet_treats";

export interface SkillDef {
  id: string;
  name: string;
  description: string;
  /** Buff skills apply `mods` for `durationMs`; instant skills fire once. */
  effect: { kind: "buff"; mods: (level: number) => Mods } | { kind: "instant"; instant: InstantEffect; power: (level: number) => number };
  cooldownMs: number;
  durationMs: number;
  maxLevel: number;
  costBase: number;
  costGrowth: number;
  unlock: UnlockRule;
  /** Visual treatment played on activation. */
  flourish: "storm" | "gold" | "surge" | "freeze" | "nova" | "calm";
  /** Level at which the ability can be set to fire itself. */
  autoLevel: number;
  synergy?: string;
}

const P = (n: number) => (level: number) => 1 + n * level;

export const SKILLS: SkillDef[] = [
  {
    id: "heart_storm",
    name: "Heart Storm",
    description: "Hearts pour into the jar for a short, loud while.",
    effect: { kind: "buff", mods: (l) => ({ mul: { all: 2 + 0.4 * l } }) },
    cooldownMs: 120_000,
    durationMs: 15_000,
    maxLevel: 25,
    costBase: 1,
    costGrowth: 1.4,
    unlock: { lifetimeHearts: 2_000 },
    flourish: "storm",
    autoLevel: 10,
  },
  {
    id: "double_love",
    name: "Double Love",
    description: "Everything counts twice.",
    effect: { kind: "buff", mods: (l) => ({ mul: { all: 2 + 0.25 * l } }) },
    cooldownMs: 90_000,
    durationMs: 20_000,
    maxLevel: 25,
    costBase: 1,
    costGrowth: 1.4,
    unlock: { lifetimeHearts: 20_000 },
    flourish: "surge",
    autoLevel: 10,
  },
  {
    id: "critical_rush",
    name: "Critical Rush",
    description: "Every tap crits while it lasts.",
    effect: { kind: "buff", mods: (l) => ({ add: { critChance: 1 }, mul: { crit: P(0.15)(l) } }) },
    cooldownMs: 180_000,
    durationMs: 12_000,
    maxLevel: 20,
    costBase: 2,
    costGrowth: 1.45,
    unlock: { lifetimeHearts: 250_000 },
    flourish: "surge",
    autoLevel: 12,
    synergy: "critical_power",
  },
  {
    id: "combo_lock",
    name: "Combo Lock",
    description: "Your combo cannot fall while this is running.",
    effect: { kind: "buff", mods: (l) => ({ add: { comboShield: 99, comboDurationMs: 30_000 }, mul: { comboPower: P(0.1)(l) } }) },
    cooldownMs: 150_000,
    durationMs: 25_000,
    maxLevel: 20,
    costBase: 2,
    costGrowth: 1.45,
    unlock: { lifetimeHearts: 400_000 },
    flourish: "freeze",
    autoLevel: 12,
  },
  {
    id: "golden_minute",
    name: "Golden Minute",
    description: "Golden hearts appear constantly for a minute.",
    effect: { kind: "buff", mods: (l) => ({ add: { goldenChance: 0.9 }, mul: { golden: P(0.2)(l) } }) },
    cooldownMs: 420_000,
    durationMs: 60_000,
    maxLevel: 20,
    costBase: 3,
    costGrowth: 1.5,
    unlock: { lifetimeHearts: 2e6 },
    flourish: "gold",
    autoLevel: 14,
  },
  {
    id: "jar_overflow",
    name: "Jar Overflow",
    description: "The jar overflows on purpose, paying out the excess.",
    effect: { kind: "instant", instant: "heart_burst", power: (l) => 60 + 25 * l },
    cooldownMs: 300_000,
    durationMs: 0,
    maxLevel: 25,
    costBase: 2,
    costGrowth: 1.45,
    unlock: { lifetimeHearts: 1e6 },
    flourish: "nova",
    autoLevel: 15,
  },
  {
    id: "pet_frenzy",
    name: "Pet Frenzy",
    description: "Your whole pet team works at once.",
    effect: { kind: "buff", mods: (l) => ({ mul: { petPower: 3 + 0.5 * l, petXp: 2 } }) },
    cooldownMs: 240_000,
    durationMs: 30_000,
    maxLevel: 20,
    costBase: 3,
    costGrowth: 1.5,
    unlock: { lifetimeHearts: 5e6 },
    flourish: "surge",
    autoLevel: 12,
  },
  {
    id: "time_freeze",
    name: "Time Freeze",
    description: "Nothing decays and nothing expires.",
    effect: { kind: "buff", mods: (l) => ({ add: { comboDurationMs: 60_000, comboShield: 99 }, mul: { skillCooldown: 1 - 0.02 * l } }) },
    cooldownMs: 480_000,
    durationMs: 20_000,
    maxLevel: 15,
    costBase: 5,
    costGrowth: 1.6,
    unlock: { rebirths: 1 },
    flourish: "freeze",
    autoLevel: 10,
  },
  {
    id: "heart_magnet",
    name: "Heart Magnet",
    description: "Pulls every floating heart straight into the jar.",
    effect: { kind: "instant", instant: "spawn_golden", power: (l) => 3 + Math.floor(l / 2) },
    cooldownMs: 200_000,
    durationMs: 0,
    maxLevel: 20,
    costBase: 3,
    costGrowth: 1.5,
    unlock: { lifetimeHearts: 8e6 },
    flourish: "gold",
    autoLevel: 12,
  },
  {
    id: "instant_charge",
    name: "Instant Charge",
    description: "Fills your energy meter to the top.",
    effect: { kind: "instant", instant: "fill_energy", power: () => 1 },
    cooldownMs: 120_000,
    durationMs: 0,
    maxLevel: 10,
    costBase: 2,
    costGrowth: 1.4,
    unlock: { lifetimeHearts: 600_000 },
    flourish: "calm",
    autoLevel: 6,
  },
  {
    id: "treasure_rain",
    name: "Treasure Rain",
    description: "Treasure hearts fall all at once.",
    effect: { kind: "instant", instant: "spawn_treasure", power: (l) => 2 + Math.floor(l / 3) },
    cooldownMs: 360_000,
    durationMs: 0,
    maxLevel: 20,
    costBase: 4,
    costGrowth: 1.55,
    unlock: { lifetimeHearts: 3e7 },
    flourish: "gold",
    autoLevel: 12,
  },
  {
    id: "lucky_burst",
    name: "Lucky Burst",
    description: "Luck spikes across everything.",
    effect: { kind: "buff", mods: (l) => ({ add: { luck: 0.5 + 0.05 * l, doubleRewardChance: 0.25 } }) },
    cooldownMs: 300_000,
    durationMs: 30_000,
    maxLevel: 20,
    costBase: 3,
    costGrowth: 1.5,
    unlock: { lifetimeHearts: 2e7 },
    flourish: "gold",
    autoLevel: 12,
  },
  {
    id: "perfect_rhythm",
    name: "Perfect Rhythm",
    description: "Every tap counts as perfectly timed.",
    effect: { kind: "buff", mods: (l) => ({ mul: { click: 3 + 0.3 * l, comboGain: 2 } }) },
    cooldownMs: 210_000,
    durationMs: 15_000,
    maxLevel: 20,
    costBase: 4,
    costGrowth: 1.55,
    unlock: { lifetimeHearts: 1e8 },
    flourish: "surge",
    autoLevel: 12,
  },
  {
    id: "upgrade_frenzy",
    name: "Upgrade Frenzy",
    description: "Grants a free level of a random affordable upgrade.",
    effect: { kind: "instant", instant: "free_upgrade", power: (l) => 1 + Math.floor(l / 5) },
    cooldownMs: 600_000,
    durationMs: 0,
    maxLevel: 20,
    costBase: 5,
    costGrowth: 1.6,
    unlock: { rebirths: 1 },
    flourish: "nova",
    autoLevel: 15,
  },
  {
    id: "discount_wave",
    name: "Discount Wave",
    description: "Prices drop sharply for a while.",
    effect: { kind: "buff", mods: (l) => ({ mul: { cost: Math.max(0.35, 0.7 - 0.015 * l) } }) },
    cooldownMs: 300_000,
    durationMs: 45_000,
    maxLevel: 20,
    costBase: 3,
    costGrowth: 1.5,
    unlock: { lifetimeHearts: 5e7 },
    flourish: "calm",
    autoLevel: 12,
  },
  {
    id: "offline_recall",
    name: "Offline Recall",
    description: "Claims another slice of the time you were away.",
    effect: { kind: "instant", instant: "offline_recall", power: (l) => 900_000 + l * 300_000 },
    cooldownMs: 900_000,
    durationMs: 0,
    maxLevel: 15,
    costBase: 4,
    costGrowth: 1.6,
    unlock: { rebirths: 1 },
    flourish: "calm",
    autoLevel: 10,
  },
  {
    id: "mission_rush",
    name: "Mission Rush",
    description: "Pushes every active mission forward.",
    effect: { kind: "instant", instant: "mission_progress", power: (l) => 0.15 + 0.02 * l },
    cooldownMs: 720_000,
    durationMs: 0,
    maxLevel: 15,
    costBase: 4,
    costGrowth: 1.6,
    unlock: { lifetimeHearts: 4e7 },
    flourish: "calm",
    autoLevel: 10,
  },
  {
    id: "challenge_breaker",
    name: "Challenge Breaker",
    description: "Advances the challenge you are running.",
    effect: { kind: "instant", instant: "challenge_progress", power: (l) => 0.1 + 0.015 * l },
    cooldownMs: 900_000,
    durationMs: 0,
    maxLevel: 15,
    costBase: 5,
    costGrowth: 1.6,
    unlock: { rebirths: 2 },
    flourish: "nova",
    autoLevel: 10,
  },
  {
    id: "boss_slayer",
    name: "Boss Heart Slayer",
    description: "A single enormous hit on the boss in front of you.",
    effect: { kind: "instant", instant: "boss_strike", power: (l) => 0.12 + 0.02 * l },
    cooldownMs: 240_000,
    durationMs: 0,
    maxLevel: 20,
    costBase: 4,
    costGrowth: 1.55,
    unlock: { lifetimeHearts: 1e7 },
    flourish: "nova",
    autoLevel: 12,
  },
  {
    id: "golden_pet_mode",
    name: "Golden Pet Mode",
    description: "Pets turn gold: more power, more treats.",
    effect: { kind: "buff", mods: (l) => ({ mul: { petPower: 2 + 0.3 * l, treatGain: 3, golden: 1.5 } }) },
    cooldownMs: 420_000,
    durationMs: 40_000,
    maxLevel: 20,
    costBase: 5,
    costGrowth: 1.6,
    unlock: { rebirths: 1 },
    flourish: "gold",
    autoLevel: 12,
  },
  {
    id: "rebirth_surge",
    name: "Rebirth Surge",
    description: "Rebirth tokens accumulate faster for a while.",
    effect: { kind: "buff", mods: (l) => ({ mul: { tokenGain: 1.5 + 0.1 * l, all: 1.5 } }) },
    cooldownMs: 900_000,
    durationMs: 60_000,
    maxLevel: 20,
    costBase: 6,
    costGrowth: 1.65,
    unlock: { rebirths: 2 },
    flourish: "nova",
    autoLevel: 14,
  },
  {
    id: "bond_overdrive",
    name: "Bond Overdrive",
    description: "Bond energy and partner bonuses spike.",
    effect: { kind: "buff", mods: (l) => ({ mul: { bondGain: 2 + 0.2 * l, all: 1.4 } }) },
    cooldownMs: 600_000,
    durationMs: 45_000,
    maxLevel: 15,
    costBase: 5,
    costGrowth: 1.6,
    unlock: { lifetimeHearts: 2e7 },
    flourish: "surge",
    autoLevel: 10,
  },
  {
    id: "lovequake",
    name: "Lovequake",
    description: "The jar shakes itself into a burst of hearts.",
    effect: { kind: "instant", instant: "heart_burst", power: (l) => 200 + 80 * l },
    cooldownMs: 600_000,
    durationMs: 0,
    maxLevel: 25,
    costBase: 6,
    costGrowth: 1.65,
    unlock: { rebirths: 2 },
    flourish: "nova",
    autoLevel: 15,
  },
  {
    id: "cosmic_heartfall",
    name: "Cosmic Heartfall",
    description: "The strongest ability in the game, and the longest wait.",
    effect: { kind: "buff", mods: (l) => ({ mul: { all: 8 + l, crit: 2, comboPower: 2, petPower: 2 } }) },
    cooldownMs: 1_800_000,
    durationMs: 30_000,
    maxLevel: 20,
    costBase: 12,
    costGrowth: 1.8,
    unlock: { ascensions: 1 },
    flourish: "nova",
    autoLevel: 15,
  },
  {
    id: "eternal_tap",
    name: "Eternal Tap",
    description: "Cooldowns reset and everything charges at once.",
    effect: { kind: "instant", instant: "reset_cooldowns", power: () => 1 },
    cooldownMs: 2_400_000,
    durationMs: 0,
    maxLevel: 10,
    costBase: 15,
    costGrowth: 1.9,
    unlock: { ascensions: 1 },
    flourish: "nova",
    autoLevel: 8,
  },
  {
    id: "memory_explosion",
    name: "Memory Explosion",
    description: "Turns the moment into memory shards and treats.",
    effect: { kind: "instant", instant: "pet_treats", power: (l) => 20 + 10 * l },
    cooldownMs: 480_000,
    durationMs: 0,
    maxLevel: 20,
    costBase: 4,
    costGrowth: 1.55,
    unlock: { lifetimeHearts: 6e7 },
    flourish: "calm",
    autoLevel: 12,
  },
];

export const SKILL_BY_ID: Record<string, SkillDef> = Object.fromEntries(SKILLS.map((s) => [s.id, s]));

export function skillCost(def: SkillDef, level: number): number {
  return Math.ceil(def.costBase * Math.pow(def.costGrowth, level));
}
